rails/config/routes.rb
Rails.application.routes.draw do
  resources :notes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/app/models/note.rb
class Note < ApplicationRecord
  has_one_attached :photo
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = Note.all.order('created_at DESC')
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    # form encoded photo from rails
    if note_params[:photo]
      @note = Note.new(note_params)
    else
      filename = 'photo.png'
      decoded_string = Base64.decode64(note_params[:data])

      tmp = Tempfile.new(filename)
      tmp.binmode
      tmp.write(decoded_string)
      tmp.rewind

      @note = Note.new
      @note.photo.attach(io: tmp, filename: filename)

      tmp.unlink
    end

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:comment, :processed, :photo, :data)
    end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/helpers/notes_helper.rb
module NotesHelper
end

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lsilmvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails/app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="field">
    <%= form.label :processed %>
    <%= form.check_box :processed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rails/app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

rails/app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Photo</th>
      <th>Comment</th>
      <th>Processed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td>
          <% if note.photo.attached? %>
            <%= image_tag(note.photo.variant(resize_to_limit: [100, 100]), height: 100, width: 100) %>
          <% else %>
            <img src="" width="100" height="100" >
          <% end %>
        </td>
        <td><%= note.comment %></td>
        <td><%= note.processed %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

rails/app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

rails/app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @note.comment %>
</p>

<p>
  <strong>Processed:</strong>
  <%= @note.processed %>
</p>

<p>
  <strong>Photo:</strong>
  <% if @note.photo.attached? %>
    <%= image_tag @note.photo.variant(resize_to_limit: [640,480]) %>
  <% else %>
    none
  <% end %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>